name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Affiche les secrets (debug)
      run: |
        echo "Host: ${{ secrets.SERVER_HOST }}"
        echo "User: ${{ secrets.SERVER_USER }}"
          echo "Connexion réussie !"