name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t tgvmaxsearcher .

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/ubuntu/webApp/deploy/tgvmaxsearcher
          GIT_SSH_COMMAND="ssh -i ~/.ssh/github_ci_key" git pull origin main
          docker build --no-cache -t tgvmaxsearcher .
          docker stop tgvmaxsearcher || true
          docker rm tgvmaxsearcher || true
          docker run -d -p 127.0.0.1:8501:8501 -v /home/ubuntu/webApp/tgvmaxsearcher/config.py:/app/config.py --name tgvmaxsearcher tgvmaxsearcher
