name: Test SSH

on:
  push:
    branches:
      - master

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Test SSH connection
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "Connexion réussie !"
